name = "EnumLinePolyenes"
uuid = "e77a8cdb-1dcd-49a0-83e2-a91192fdd951"
authors = ["Yurii Nosov"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1.14.1"
Plots = "1.41.1"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
